# HYPOTHESIS TESTING

In [63]:
#importing necessary libraries
import numpy as np
import pandas as pd
from scipy import stats


# cutlets statement

Defining null and alternate hypothesis


H0: Diameter of unit A == Diameter of Unit B


H1: Diameter of unit A != Diameter of Unit B


Siginificance level alpha =0.05 
Confidence interval =0.95

if p value < aplha we reject null hypothesis

elif p value > alpha we reject alternate hyothesis


Test type : two sample Independent t test

In [64]:
#reading the file
cutlets_df=pd.read_csv('Cutlets.csv')

In [65]:
#overview of te data
cutlets_df.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [66]:
#defining alpha=0.05
alpha=0.05

In [67]:
#imprting ttest_ind from stats library 
stats.ttest_ind(cutlets_df['Unit A'],cutlets_df['Unit B'])

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [68]:
#storing test statistic value and p value in two variables
ttest_ind,p_cutlets=stats.ttest_ind(cutlets_df['Unit A'],cutlets_df['Unit B'])

In [69]:
#displaying results
print('ttest_ind statistic is :',ttest_ind)
print('pvalue of ttset_ind is :',p_cutlets)

ttest_ind statistic is : 0.7228688704678063
pvalue of ttset_ind is : 0.4722394724599501


In [70]:
#checking the hypothesis
if p_cutlets<alpha:
    print('reject null hypothesis')
elif p_cutlets>alpha:
    print('reject alternate hypothesis')

reject alternate hypothesis


Conclusion:

     1)we reject alternate hypothesis.
     
     2)According to the problem statement the diameters of two units unit A and Unit B  are equal as per the hypothesis test carried out.

# LAB TAT STATEMENT


Defining null and alternate hypothesis

H0: ATAT  of lab1 == lab2 == lab3 == lab4

H1: ATAT of lab1 != lab2 != lab3 != lab4

Siginificance level alpha =0.05 Confidence interval =0.95

if p value < aplha we reject null hypothesis

elif p value > alpha we reject alternate hyothesis

Test type : Anova test

In [71]:
#reading the data
lab_df=pd.read_csv('LabTAT.csv')

In [72]:
#overview od data
lab_df.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [73]:
#importing f_oneway test from stats library
stats.f_oneway(lab_df.iloc[:,0],lab_df.iloc[:,1],lab_df.iloc[:,2],lab_df.iloc[:,3])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [74]:
#storing test statistic value and p value in two variables
f_test_statistic,p_anova=stats.f_oneway(lab_df.iloc[:,0],lab_df.iloc[:,1],lab_df.iloc[:,2],lab_df.iloc[:,3])

In [75]:
#displaying results
print('f_test statistic is :',f_test_statistic)
print('pvalue of anova test is :',p_anova)

f_test statistic is : 118.70421654401437
pvalue of anova test is : 2.1156708949992414e-57


In [76]:
#checking the hypothesis
if p_anova<alpha:
    print('reject null hypothesis')
elif p_anova>alpha:
    print('reject alternate hypothesis')

reject null hypothesis


Conclusion:

     1)we reject null hypothesis.
     
     2)According to the problem statement the ATAT of 4 labs are not equal.

# Buyer ratio statement

Defining null and alternate hypothesis

H0: no relationship b/w variables

H1: exists a relationship b/w variables

Siginificance level alpha =0.05 Confidence interval =0.95

if chi-square statistic score <critical value:
                              
    accept ho

elif chi_square statistic score>critical value:
    
    
    accept h1

Test type : Chisquare test

In [77]:
#reading the data
buyratio_df=pd.read_csv('BuyerRatio.csv')
buyratio_df.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [78]:
#getting observed values in array 
buyratio_values=buyratio_df.values[:,1:]
buyratio_values

array([[50, 142, 131, 70],
       [435, 1523, 1356, 750]], dtype=object)

In [79]:
#getting 
val=stats.chi2_contingency(buyratio_values)

In [80]:
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [43]:
#separating expected values
expected_values=val[3]
expected_values


array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [55]:
#calculating degrees of freedom
rows=buyratio_df.shape[0]
columns=len(buyratio_df.columns)-1
ddof=(rows-1)*(columns-1)
print('degrees of freedom :',ddof)

degrees of freedom : 3


In [58]:
#calculating chisquare score
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(buyratio_values,expected_values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [59]:
print('chi square statistic value :',chi_square_statistic)

chi square statistic value : 1.5152956451130446


In [60]:
#calculating critical value
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical value :',critical_value)

critical value : 7.814727903251179


In [62]:
#checking the hypothesis
if chi_square_statistic<critical_value:
    print('reject alternate hypothesis')
elif chi_square_statistic>critical_value:
    print('reject null hypothesis')

reject alternate hypothesis


Conclusion:

     1)we reject alternate hypothesis.
     
     2)According to the problem statement and by performing hypothesis testing we found there is a relationship between                variables.

# customer order statement

Defining null and alternate hypothesis

H0: defective %  of Phillippines ==	Indonesia == Malta ==	India

H1: defective %  of Phillippines !=	Indonesia != Malta !=	India

Siginificance level alpha =0.05 Confidence interval =0.95

if p value < aplha we reject null hypothesis

elif p value > alpha we reject alternate hyothesis

Test type : Anova test

In [89]:
#reading the data
customer_df=pd.read_csv('Costomer+OrderForm.csv')

In [90]:
#overview of data
customer_df.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [118]:
#creating dummies
customer_defective=pd.get_dummies(customer_df)

In [122]:
customer_defective=customer_defective.loc[:,('Phillippines_Defective','Indonesia_Defective','Malta_Defective','India_Defective')]
customer_defective.head()

Phillippines_Defective  Indonesia_Defective  Malta_Defective  \
0                       0                    0                1   
1                       0                    0                0   
2                       0                    1                1   
3                       0                    0                0   
4                       0                    0                1   

   India_Defective  
0                0  
1                1  
2                0  
3                0  
4                0

In [123]:
#importing f_oneway test from stats library
stats.f_oneway(customer_defective.iloc[:,0],customer_defective.iloc[:,1],customer_defective.iloc[:,2],customer_defective.iloc[:,3])

F_onewayResult(statistic=1.286168556089167, pvalue=0.2776780955705948)

In [127]:
#storing test statistic value and p value in two variables
f_test_statistic_defective,p_anova_defective=stats.f_oneway(customer_defective.iloc[:,0],customer_defective.iloc[:,1],customer_defective.iloc[:,2],customer_defective.iloc[:,3])

In [128]:
#displaying results
print('f_test statistic  is :',f_test_statistic_defective)
print('pvalue of anova test is :',p_anova_defective)


f_test statistic  is : 1.286168556089167
pvalue of anova test is : 0.2776780955705948


In [129]:
#checking the hypothesis
if p_anova<alpha:
    print('reject null hypothesis')
elif p_anova>alpha:
    print('reject alternate hypothesis')

reject null hypothesis


Conclusion:

     1)we reject null hypothesis.
     
     2)According to the problem statement the defective % of 4 centers are not equal.

Hence we performed the hypothesis testing for all problem statements and drawn conclusions to take necessary decisions.
                                                                                      
                                                                                                      
                                                                                               

#                                                           
                                                                                     K.SUMAN KUMAR